<?php declare(strict_types=1);
set_error_handler(function(int $n,string $s,string $f,int $l){if(!(error_reporting()&$n))return false;throw new \ErrorException($s,0,$n,$f,$l);});
set_exception_handler(function(\Throwable $e){error_log($e->getMessage()." in ".$e->getFile().":".$e->getLine());if(headers_sent()){echo"<div class=\"p-4 bg-red-50 text-red-700 rounded m-4\">".htmlspecialchars($e->getMessage())."</div>";return;}http_response_code(500);echo"<!DOCTYPE html><html><head><title>Error</title><script src=\"https://cdn.tailwindcss.com\"></script></head><body class=\"bg-slate-50 flex items-center justify-center min-h-screen\"><div class=\"text-center\"><h1 class=\"text-2xl font-bold text-slate-800 mb-2\">Something went wrong</h1><p class=\"text-slate-500 mb-4\">".htmlspecialchars($e->getMessage())."</p><a href=\"index.php\" class=\"px-6 py-2 bg-indigo-600 text-white rounded-lg\">Go Home</a></div></body></html>";});
if(session_status()===PHP_SESSION_NONE)session_start();
require_once __DIR__."/config/app.php";
require_once __DIR__."/core/Database.php";
require_once __DIR__."/core/EventBus.php";
require_once __DIR__."/core/AuditLogger.php";
require_once __DIR__."/core/StateMachine.php";
require_once __DIR__."/core/BaseModel.php";
require_once __DIR__."/core/RBACMiddleware.php";
require_once __DIR__."/core/BaseController.php";
require_once __DIR__."/core/Router.php";
require_once __DIR__."/core/EmailService.php";
foreach(glob(__DIR__."/models/*.php") as $f)require_once $f;
foreach(glob(__DIR__."/services/*/*.php") as $f)require_once $f;
$eb=EventBus::getInstance();
$eb->subscribe("RedFlagRaised",function(array $p){if(($p["severity"]??"")=="critical"){(new ApplicationModel())->update((int)$p["application_id"],["is_frozen"=>1]);}});
$eb->subscribe("JobApprovedEvent",function(array $p){try{(new JobBoardSyncService())->syncToAll((int)$p["job_id"]);}catch(\Exception $e){error_log("Sync:".$e->getMessage());}});
Router::dispatch();